name: CD Docker Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Semantic version of the release'
        required: true
  pull_request:
  push:
    branches:
      - 'main'

env:
  DBT_TERADATA_VERSION: ${{ github.event.inputs.releaseVersion }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        shell: bash
        run: |
          find .
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          build-args: |
          tags: teradata/dbt-teradata:latest, teradata/dbt-teradata:${{ env.DBT_TERADATA_VERSION }}
