name: CD Release TESTPYPI
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Semantic version of the release'
        required: true

jobs:
  cdRelease:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Upload to PyPi
        shell: bash
        run: |
          rm -fr dist/*
          python setup.py sdist bdist_wheel
          twine upload testpypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.releaseVersion }}
          release_name: dbt-teradata v${{ github.event.inputs.releaseVersion }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: false
      - name: reset changelog
        shell: bash
        run: |
          git checkout main
          cp CHANGELOG.md.template CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "resetting CHANGELOG.md for the next release"
          git push
