name: CD Release TESTPYPI
on:
  workflow_dispatch:
  
jobs:
  cdReleaseTestpypi:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Upload to PyPi
        shell: bash
        run: |
          rm -fr dist/*
          python setup.py sdist bdist_wheel
          twine upload --repository dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }}
