name: CI Docker Integration Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  cdRelease:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Docker
        shell: bash
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo docker run hello-world
