name: Docker Image CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'

env:
  DBT_TERADATA_VERSION: ${{ github.event.inputs.releaseVersion }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          build-args: |
          tags: teradata/dbt-teradata:latest, teradata/dbt-teradata:${{ env.DBT_TERADATA_VERSION }}
