name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: linux/amd64

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker_dev/Dockerfile --tag dbt-teradata:1.2.0

